name: dcatact
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_static: ^1.1.2

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.15.0
  test_process: ^2.0.0
